import {
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  onSnapshot,
  serverTimestamp,
  setDoc,
  Timestamp,
  updateDoc,
  writeBatch,
  type DocumentData,
  type Unsubscribe,
} from "firebase/firestore";
import type { ApplicationStatus } from "@/constants/application-statuses";
import { COLLECTIONS } from "@/constants/firestore";
import { getFirebaseAuth, getFirebaseDb } from "@/lib/firebase/client";
import type { CreateApplicationInput, UpdateApplicationInput } from "@/schemas/application.schema";
import type { Application, StatusHistoryEntry } from "@/types/application";

/**
 * Normalizes document data from Firestore into the Application interface.
 * Handles both subcollection formats, Firestore Timestamps, and ISO date strings.
 */
function mapDocToApplication(id: string, userId: string, data: DocumentData): Application {
  const companyName = String(data.companyName ?? data.company ?? "");
  const appliedDate = data.appliedDate ?? data.appliedAt ?? null;

  let appliedAtStr: string | null = null;
  if (appliedDate) {
    if (typeof appliedDate.toDate === "function") {
      appliedAtStr = appliedDate.toDate().toISOString().slice(0, 10);
    } else if (appliedDate instanceof Date) {
      appliedAtStr = appliedDate.toISOString().slice(0, 10);
    } else if (typeof appliedDate === "string") {
      appliedAtStr = appliedDate.slice(0, 10);
    }
  }

  let createdAtStr = new Date().toISOString();
  if (data.createdAt) {
    if (typeof data.createdAt.toDate === "function") {
      createdAtStr = data.createdAt.toDate().toISOString();
    } else if (data.createdAt instanceof Date) {
      createdAtStr = data.createdAt.toISOString();
    } else if (typeof data.createdAt === "string") {
      createdAtStr = data.createdAt;
    }
  }

  let updatedAtStr = createdAtStr;
  if (data.updatedAt) {
    if (typeof data.updatedAt.toDate === "function") {
      updatedAtStr = data.updatedAt.toDate().toISOString();
    } else if (data.updatedAt instanceof Date) {
      updatedAtStr = data.updatedAt.toISOString();
    } else if (typeof data.updatedAt === "string") {
      updatedAtStr = data.updatedAt;
    }
  }

  return {
    id,
    userId: data.userId || userId,
    company: companyName,
    companyName,
    jobTitle: String(data.jobTitle || ""),
    source: data.source || "other",
    status: data.status || "saved",
    appliedDate: data.appliedDate ?? (appliedAtStr ? Timestamp.fromDate(new Date(appliedAtStr)) : null),
    appliedAt: appliedAtStr,
    location: data.location ?? null,
    resumeUrl: data.resumeUrl ?? null,
    resumeName: data.resumeName ?? null,
    jobUrl: data.jobUrl ?? null,
    resumeId: data.resumeId ?? null,
    jobDescriptionSnapshot: data.jobDescriptionSnapshot ?? null,
    jobDescriptionCapturedAt: data.jobDescriptionCapturedAt ?? null,
    notes: data.notes ?? null,
    createdAt: createdAtStr,
    updatedAt: updatedAtStr,
  };
}

/**
 * Safely extracts timestamp in milliseconds for sorting applications.
 */
function getAppTimestamp(app: Application): number {
  if (app.appliedDate) {
    if (typeof (app.appliedDate as { toMillis?: () => number }).toMillis === "function") {
      return (app.appliedDate as { toMillis: () => number }).toMillis();
    }
    if (app.appliedDate instanceof Date) {
      return app.appliedDate.getTime();
    }
  }
  if (app.appliedAt) {
    const parsed = new Date(app.appliedAt).getTime();
    if (!isNaN(parsed)) return parsed;
  }
  if (app.createdAt) {
    if (typeof (app.createdAt as unknown as { toMillis?: () => number })?.toMillis === "function") {
      return (app.createdAt as unknown as { toMillis: () => number }).toMillis();
    }
    const parsed = new Date(app.createdAt).getTime();
    if (!isNaN(parsed)) return parsed;
  }
  return 0;
}

function sortApplications(apps: Application[]): Application[] {
  return [...apps].sort((a, b) => getAppTimestamp(b) - getAppTimestamp(a));
}

function getEffectiveUserId(userId?: string): string {
  if (userId) return userId;
  const currentUid = getFirebaseAuth().currentUser?.uid;
  if (!currentUid) {
    throw new Error("User must be authenticated to perform this operation.");
  }
  return currentUid;
}

/**
 * Cloud Firestore client data-access layer for applications.
 * All application operations target: users/{authenticatedUid}/applications/{autoGeneratedApplicationId}
 * Strictly complies with `firebase/firestore.rules` and document ownership constraints.
 */
export const applicationService = {
  /**
   * Creates an application document under users/{uid}/applications/{applicationId}.
   * Uses Firestore-generated ID and server timestamps.
   */
  createApplication: async (
    first: string | CreateApplicationInput,
    second?: CreateApplicationInput | string,
  ): Promise<Application> => {
    let uid: string;
    let input: CreateApplicationInput;

    if (typeof first === "string") {
      uid = first;
      input = second as CreateApplicationInput;
    } else {
      input = first;
      uid = typeof second === "string" ? second : getEffectiveUserId();
    }

    const db = getFirebaseDb();
    const colRef = collection(db, COLLECTIONS.users, uid, COLLECTIONS.applications);
    const appRef = doc(colRef);
    const now = new Date();
    const nowIso = now.toISOString();

    const company = (input.companyName || input.company || "").trim();
    const appliedDateVal = (input as Record<string, unknown>).appliedDate;
    let appliedDateTimestamp: Timestamp;
    let appliedAtString: string | null = null;

    if (appliedDateVal) {
      if (appliedDateVal instanceof Date) {
        appliedDateTimestamp = Timestamp.fromDate(appliedDateVal);
        appliedAtString = appliedDateVal.toISOString().slice(0, 10);
      } else if (typeof appliedDateVal === "string") {
        appliedDateTimestamp = Timestamp.fromDate(new Date(appliedDateVal));
        appliedAtString = appliedDateVal.slice(0, 10);
      } else if (typeof (appliedDateVal as { toDate?: () => Date }).toDate === "function") {
        appliedDateTimestamp = appliedDateVal as Timestamp;
        appliedAtString = (appliedDateVal as Timestamp).toDate().toISOString().slice(0, 10);
      } else {
        appliedDateTimestamp = Timestamp.fromDate(now);
        appliedAtString = nowIso.slice(0, 10);
      }
    } else if (input.appliedAt) {
      appliedDateTimestamp = Timestamp.fromDate(new Date(input.appliedAt));
      appliedAtString = input.appliedAt.slice(0, 10);
    } else {
      appliedDateTimestamp = Timestamp.fromDate(now);
      appliedAtString = nowIso.slice(0, 10);
    }

    const applicationData = {
      id: appRef.id,
      userId: uid,
      company,
      companyName: company,
      jobTitle: input.jobTitle.trim(),
      source: input.source,
      status: input.status || "saved",
      appliedDate: appliedDateTimestamp,
      appliedAt: appliedAtString,
      location: input.location?.trim() || null,
      resumeName: input.resumeName?.trim() || null,
      resumeUrl: (input as Record<string, unknown>).resumeUrl ? String((input as Record<string, unknown>).resumeUrl) : null,
      resumeId: input.resumeId || null,
      jobUrl: input.jobUrl || null,
      jobDescriptionSnapshot: input.jobDescriptionSnapshot || null,
      jobDescriptionCapturedAt: input.jobDescriptionSnapshot ? nowIso : null,
      notes: input.notes || null,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };

    await setDoc(appRef, applicationData);

    return {
      ...applicationData,
      createdAt: nowIso,
      updatedAt: nowIso,
    } as Application;
  },

  /** Alias for createApplication */
  create: async (userId: string, input: CreateApplicationInput): Promise<Application> => {
    return applicationService.createApplication(userId, input);
  },

  /**
   * Fetches all applications for the authenticated user from users/{uid}/applications.
   */
  getApplications: async (userId?: string): Promise<Application[]> => {
    const uid = getEffectiveUserId(userId);
    const db = getFirebaseDb();
    const colRef = collection(db, COLLECTIONS.users, uid, COLLECTIONS.applications);
    const snap = await getDocs(colRef);
    const apps = snap.docs.map((d) => mapDocToApplication(d.id, uid, d.data()));
    return sortApplications(apps);
  },

  /** Alias for getApplications */
  list: async (userId?: string): Promise<Application[]> => {
    return applicationService.getApplications(userId);
  },

  /**
   * Retrieves a single application from users/{uid}/applications/{applicationId}.
   */
  getApplication: async (applicationId: string, userId?: string): Promise<Application | null> => {
    const uid = getEffectiveUserId(userId);
    const db = getFirebaseDb();
    const docRef = doc(db, COLLECTIONS.users, uid, COLLECTIONS.applications, applicationId);
    const snap = await getDoc(docRef);
    if (!snap.exists()) return null;
    return mapDocToApplication(snap.id, uid, snap.data());
  },

  /** Alias for getApplication */
  getById: async (id: string, userId?: string): Promise<Application | null> => {
    return applicationService.getApplication(id, userId);
  },

  /**
   * Updates an application document at users/{uid}/applications/{applicationId}.
   */
  updateApplication: async (
    applicationId: string,
    input: UpdateApplicationInput | Partial<Application>,
    userId?: string,
  ): Promise<void> => {
    const uid = getEffectiveUserId(userId);
    const db = getFirebaseDb();
    const docRef = doc(db, COLLECTIONS.users, uid, COLLECTIONS.applications, applicationId);

    const updates: Record<string, unknown> = {
      updatedAt: serverTimestamp(),
    };

    const company = (input as Record<string, unknown>).companyName ?? (input as Record<string, unknown>).company;
    if (company !== undefined && typeof company === "string") {
      updates.company = company.trim();
      updates.companyName = company.trim();
    }
    if (input.jobTitle !== undefined && typeof input.jobTitle === "string") {
      updates.jobTitle = input.jobTitle.trim();
    }
    if ((input as Record<string, unknown>).appliedDate !== undefined) {
      const val = (input as Record<string, unknown>).appliedDate;
      if (val) {
        if (val instanceof Date) {
          updates.appliedDate = Timestamp.fromDate(val);
          updates.appliedAt = val.toISOString().slice(0, 10);
        } else if (typeof val === "string") {
          updates.appliedDate = Timestamp.fromDate(new Date(val));
          updates.appliedAt = val.slice(0, 10);
        } else {
          updates.appliedDate = val;
        }
      } else {
        updates.appliedDate = null;
        updates.appliedAt = null;
      }
    } else if (input.appliedAt !== undefined) {
      updates.appliedAt = input.appliedAt;
      updates.appliedDate = input.appliedAt ? Timestamp.fromDate(new Date(input.appliedAt)) : null;
    }
    if (input.source !== undefined) updates.source = input.source;
    if (input.jobUrl !== undefined) updates.jobUrl = input.jobUrl;
    if (input.resumeId !== undefined) updates.resumeId = input.resumeId;
    if (input.location !== undefined) updates.location = input.location?.trim() || null;
    if (input.resumeName !== undefined) updates.resumeName = input.resumeName?.trim() || null;
    if ((input as Record<string, unknown>).resumeUrl !== undefined) {
      updates.resumeUrl = (input as Record<string, unknown>).resumeUrl || null;
    }
    if (input.jobDescriptionSnapshot !== undefined) {
      updates.jobDescriptionSnapshot = input.jobDescriptionSnapshot;
      if (input.jobDescriptionSnapshot) {
        updates.jobDescriptionCapturedAt = new Date().toISOString();
      }
    }
    if (input.notes !== undefined) updates.notes = input.notes;

    await updateDoc(docRef, updates);
  },

  /** Alias for updateApplication */
  update: async (
    id: string,
    input: UpdateApplicationInput | Partial<Application>,
    userId?: string,
  ): Promise<void> => {
    return applicationService.updateApplication(id, input, userId);
  },

  /**
   * Deletes an application document from users/{uid}/applications/{applicationId}.
   */
  deleteApplication: async (applicationId: string, userId?: string): Promise<void> => {
    const uid = getEffectiveUserId(userId);
    const db = getFirebaseDb();
    const docRef = doc(db, COLLECTIONS.users, uid, COLLECTIONS.applications, applicationId);
    await deleteDoc(docRef);
  },

  /** Alias for deleteApplication */
  delete: async (id: string, userId?: string): Promise<void> => {
    return applicationService.deleteApplication(id, userId);
  },

  /**
   * Subscribes to real-time changes to the user's applications collection.
   * Path: users/{uid}/applications
   */
  subscribeToApplications: (
    userIdOrUpdate: string | ((applications: Application[]) => void),
    maybeOnUpdate?: (applications: Application[]) => void,
    onError?: (err: Error) => void,
  ): Unsubscribe => {
    let uid: string;
    let onUpdate: (applications: Application[]) => void;
    let errorHandler = onError;

    if (typeof userIdOrUpdate === "string") {
      uid = userIdOrUpdate;
      onUpdate = maybeOnUpdate!;
    } else {
      uid = getEffectiveUserId();
      onUpdate = userIdOrUpdate;
    }

    const db = getFirebaseDb();
    const colRef = collection(db, COLLECTIONS.users, uid, COLLECTIONS.applications);

    return onSnapshot(
      colRef,
      (snapshot) => {
        const apps = snapshot.docs.map((d) => mapDocToApplication(d.id, uid, d.data()));
        onUpdate(sortApplications(apps));
      },
      (err) => {
        console.error("Firestore applications subscription error:", err);
        errorHandler?.(err);
      },
    );
  },

  /** Alias for subscribeToApplications */
  subscribe: (
    userId: string,
    onUpdate: (applications: Application[]) => void,
    onError?: (err: Error) => void,
  ): Unsubscribe => {
    return applicationService.subscribeToApplications(userId, onUpdate, onError);
  },

  /**
   * Atomically changes application status in users/{uid}/applications/{id} and appends statusHistory.
   */
  changeStatus: async (
    id: string,
    userId: string,
    toStatus: ApplicationStatus,
    fromStatus: ApplicationStatus | null,
    note?: string | null,
  ): Promise<void> => {
    const uid = getEffectiveUserId(userId);
    const db = getFirebaseDb();
    const batch = writeBatch(db);
    const now = new Date().toISOString();

    const appRef = doc(db, COLLECTIONS.users, uid, COLLECTIONS.applications, id);
    batch.update(appRef, { status: toStatus, updatedAt: serverTimestamp() });

    const historyRef = doc(collection(db, COLLECTIONS.statusHistory));
    const historyEntry: StatusHistoryEntry = {
      id: historyRef.id,
      userId: uid,
      applicationId: id,
      fromStatus: fromStatus ?? null,
      toStatus,
      changedAt: now,
      note: note || `Status updated to ${toStatus}`,
    };
    batch.set(historyRef, historyEntry);

    await batch.commit();
  },

  /**
   * Retrieves full status history for an application.
   */
  listStatusHistory: async (applicationId: string): Promise<StatusHistoryEntry[]> => {
    const db = getFirebaseDb();
    const q = collection(db, COLLECTIONS.statusHistory);
    const snap = await getDocs(q);
    const entries = snap.docs
      .map((d) => ({ ...d.data(), id: d.id }) as StatusHistoryEntry)
      .filter((e) => e.applicationId === applicationId);
    return entries.sort((a, b) => b.changedAt.localeCompare(a.changedAt));
  },

  /**
   * Seeds demo applications to the authenticated user's subcollection.
   */
  seedDemoApplications: async (userId?: string): Promise<void> => {
    const uid = getEffectiveUserId(userId);
    const demoItems: CreateApplicationInput[] = [
      {
        company: "Google",
        companyName: "Google",
        jobTitle: "Software Engineer",
        location: "Mountain View, CA • Hybrid",
        appliedAt: "2025-04-22",
        status: "interview",
        resumeName: "React Dev v3.pdf",
        source: "linkedin",
        jobUrl: "https://careers.google.com/jobs/results/123",
        notes: "Technical interview scheduled.",
      },
      {
        company: "Microsoft",
        companyName: "Microsoft",
        jobTitle: "Frontend Developer",
        location: "Redmond, WA • Remote",
        appliedAt: "2025-04-20",
        status: "screening",
        resumeName: "Frontend v2.pdf",
        source: "company_portal",
        jobUrl: "https://careers.microsoft.com",
        notes: "Recruiter screening on Friday.",
      },
      {
        company: "Amazon",
        companyName: "Amazon",
        jobTitle: "SDE Intern",
        location: "Bengaluru, India • On-site",
        appliedAt: "2025-04-18",
        status: "applied",
        resumeName: "Resume v1.pdf",
        source: "naukri",
        jobUrl: "https://amazon.jobs",
        notes: "Applied via online portal.",
      },
    ];

    for (const item of demoItems) {
      await applicationService.createApplication(uid, item);
    }
  },
};
